/*
Attio API

Testing CommentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package libattio

import (
	"context"
	libattio "github.com/fastah/libattio"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_libattio_CommentsAPIService(t *testing.T) {

	configuration := libattio.NewConfiguration()
	apiClient := libattio.NewAPIClient(configuration)

	t.Run("Test CommentsAPIService V2CommentsCommentIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var commentId string

		resp, httpRes, err := apiClient.CommentsAPI.V2CommentsCommentIdDelete(context.Background(), commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CommentsAPIService V2CommentsCommentIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var commentId string

		resp, httpRes, err := apiClient.CommentsAPI.V2CommentsCommentIdGet(context.Background(), commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CommentsAPIService V2CommentsPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CommentsAPI.V2CommentsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
