/*
Attio API

Testing WebhooksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package libattio

import (
	"context"
	libattio "github.com/fastah/libattio"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_libattio_WebhooksAPIService(t *testing.T) {

	configuration := libattio.NewConfiguration()
	apiClient := libattio.NewAPIClient(configuration)

	t.Run("Test WebhooksAPIService V2WebhooksGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.WebhooksAPI.V2WebhooksGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksAPIService V2WebhooksPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.WebhooksAPI.V2WebhooksPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksAPIService V2WebhooksWebhookIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksAPI.V2WebhooksWebhookIdDelete(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksAPIService V2WebhooksWebhookIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksAPI.V2WebhooksWebhookIdGet(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksAPIService V2WebhooksWebhookIdPatch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksAPI.V2WebhooksWebhookIdPatch(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
