/*
Attio API

Testing FilesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package libattio

import (
	"context"
	"testing"

	libattio "github.com/sid6mathur/libattio"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_libattio_FilesAPIService(t *testing.T) {

	configuration := libattio.NewConfiguration()
	apiClient := libattio.NewAPIClient(configuration)

	t.Run("Test FilesAPIService V2FilesFileIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string

		resp, httpRes, err := apiClient.FilesAPI.V2FilesFileIdDelete(context.Background(), fileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService V2FilesFileIdDownloadGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string

		httpRes, err := apiClient.FilesAPI.V2FilesFileIdDownloadGet(context.Background(), fileId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService V2FilesFileIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string

		resp, httpRes, err := apiClient.FilesAPI.V2FilesFileIdGet(context.Background(), fileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService V2FilesGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FilesAPI.V2FilesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService V2FilesPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FilesAPI.V2FilesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService V2FilesUploadPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FilesAPI.V2FilesUploadPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
