/*
Attio API

Testing WorkspaceMembersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package libattio

import (
	"context"
	libattio "github.com/fastah/libattio"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_libattio_WorkspaceMembersAPIService(t *testing.T) {

	configuration := libattio.NewConfiguration()
	apiClient := libattio.NewAPIClient(configuration)

	t.Run("Test WorkspaceMembersAPIService V2WorkspaceMembersGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.WorkspaceMembersAPI.V2WorkspaceMembersGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspaceMembersAPIService V2WorkspaceMembersWorkspaceMemberIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var workspaceMemberId string

		resp, httpRes, err := apiClient.WorkspaceMembersAPI.V2WorkspaceMembersWorkspaceMemberIdGet(context.Background(), workspaceMemberId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
