/*
Attio API

Testing ObjectsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package libattio

import (
	"context"
	libattio "github.com/fastah/libattio"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_libattio_ObjectsAPIService(t *testing.T) {

	configuration := libattio.NewConfiguration()
	apiClient := libattio.NewAPIClient(configuration)

	t.Run("Test ObjectsAPIService V2ObjectsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ObjectsAPI.V2ObjectsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ObjectsAPIService V2ObjectsObjectGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var object string

		resp, httpRes, err := apiClient.ObjectsAPI.V2ObjectsObjectGet(context.Background(), object).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ObjectsAPIService V2ObjectsObjectPatch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var object string

		resp, httpRes, err := apiClient.ObjectsAPI.V2ObjectsObjectPatch(context.Background(), object).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ObjectsAPIService V2ObjectsPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ObjectsAPI.V2ObjectsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
