/*
Attio API

Testing CallRecordingsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package libattio

import (
	"context"
	libattio "github.com/sid6mathur/libattio"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_libattio_CallRecordingsAPIService(t *testing.T) {

	configuration := libattio.NewConfiguration()
	apiClient := libattio.NewAPIClient(configuration)

	t.Run("Test CallRecordingsAPIService V2MeetingsMeetingIdCallRecordingsCallRecordingIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var meetingId string
		var callRecordingId string

		resp, httpRes, err := apiClient.CallRecordingsAPI.V2MeetingsMeetingIdCallRecordingsCallRecordingIdDelete(context.Background(), meetingId, callRecordingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CallRecordingsAPIService V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var meetingId string
		var callRecordingId string

		resp, httpRes, err := apiClient.CallRecordingsAPI.V2MeetingsMeetingIdCallRecordingsCallRecordingIdGet(context.Background(), meetingId, callRecordingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CallRecordingsAPIService V2MeetingsMeetingIdCallRecordingsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var meetingId string

		resp, httpRes, err := apiClient.CallRecordingsAPI.V2MeetingsMeetingIdCallRecordingsGet(context.Background(), meetingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CallRecordingsAPIService V2MeetingsMeetingIdCallRecordingsPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var meetingId string

		resp, httpRes, err := apiClient.CallRecordingsAPI.V2MeetingsMeetingIdCallRecordingsPost(context.Background(), meetingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
