/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"fmt"
)

// V2FilesPostRequest struct for V2FilesPostRequest
type V2FilesPostRequest struct {
	ConnectedFile   *ConnectedFile
	ConnectedFolder *ConnectedFolder
	Folder          *Folder
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *V2FilesPostRequest) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ConnectedFile
	err = json.Unmarshal(data, &dst.ConnectedFile)
	if err == nil {
		jsonConnectedFile, _ := json.Marshal(dst.ConnectedFile)
		if string(jsonConnectedFile) == "{}" { // empty struct
			dst.ConnectedFile = nil
		} else {
			return nil // data stored in dst.ConnectedFile, return on the first match
		}
	} else {
		dst.ConnectedFile = nil
	}

	// try to unmarshal JSON data into ConnectedFolder
	err = json.Unmarshal(data, &dst.ConnectedFolder)
	if err == nil {
		jsonConnectedFolder, _ := json.Marshal(dst.ConnectedFolder)
		if string(jsonConnectedFolder) == "{}" { // empty struct
			dst.ConnectedFolder = nil
		} else {
			return nil // data stored in dst.ConnectedFolder, return on the first match
		}
	} else {
		dst.ConnectedFolder = nil
	}

	// try to unmarshal JSON data into Folder
	err = json.Unmarshal(data, &dst.Folder)
	if err == nil {
		jsonFolder, _ := json.Marshal(dst.Folder)
		if string(jsonFolder) == "{}" { // empty struct
			dst.Folder = nil
		} else {
			return nil // data stored in dst.Folder, return on the first match
		}
	} else {
		dst.Folder = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(V2FilesPostRequest)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V2FilesPostRequest) MarshalJSON() ([]byte, error) {
	if src.ConnectedFile != nil {
		return json.Marshal(&src.ConnectedFile)
	}

	if src.ConnectedFolder != nil {
		return json.Marshal(&src.ConnectedFolder)
	}

	if src.Folder != nil {
		return json.Marshal(&src.Folder)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableV2FilesPostRequest struct {
	value *V2FilesPostRequest
	isSet bool
}

func (v NullableV2FilesPostRequest) Get() *V2FilesPostRequest {
	return v.value
}

func (v *NullableV2FilesPostRequest) Set(val *V2FilesPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV2FilesPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV2FilesPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2FilesPostRequest(val *V2FilesPostRequest) *NullableV2FilesPostRequest {
	return &NullableV2FilesPostRequest{value: val, isSet: true}
}

func (v NullableV2FilesPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2FilesPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
