/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"fmt"
)

// V2TargetIdentifierAttributesPostRequestDataDefaultValue The default value for this attribute. Static values are used to directly populate values using their contents. Dynamic values are used to lookup data at the point of creation. For example, you could use a dynamic value to insert a value for the currently logged in user. Which default values are available is dependent on the type of the attribute. Default values are not currently supported on people or company objects.
type V2TargetIdentifierAttributesPostRequestDataDefaultValue struct {
	V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf  *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf
	V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *V2TargetIdentifierAttributesPostRequestDataDefaultValue) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf
	err = json.Unmarshal(data, &dst.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf)
	if err == nil {
		jsonV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf, _ := json.Marshal(dst.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf)
		if string(jsonV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) == "{}" { // empty struct
			dst.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf = nil
		} else {
			return nil // data stored in dst.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf, return on the first match
		}
	} else {
		dst.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf = nil
	}

	// try to unmarshal JSON data into V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1
	err = json.Unmarshal(data, &dst.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1)
	if err == nil {
		jsonV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1, _ := json.Marshal(dst.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1)
		if string(jsonV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) == "{}" { // empty struct
			dst.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 = nil
		} else {
			return nil // data stored in dst.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1, return on the first match
		}
	} else {
		dst.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(V2TargetIdentifierAttributesPostRequestDataDefaultValue)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V2TargetIdentifierAttributesPostRequestDataDefaultValue) MarshalJSON() ([]byte, error) {
	if src.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf != nil {
		return json.Marshal(&src.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf)
	}

	if src.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 != nil {
		return json.Marshal(&src.V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableV2TargetIdentifierAttributesPostRequestDataDefaultValue struct {
	value *V2TargetIdentifierAttributesPostRequestDataDefaultValue
	isSet bool
}

func (v NullableV2TargetIdentifierAttributesPostRequestDataDefaultValue) Get() *V2TargetIdentifierAttributesPostRequestDataDefaultValue {
	return v.value
}

func (v *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValue) Set(val *V2TargetIdentifierAttributesPostRequestDataDefaultValue) {
	v.value = val
	v.isSet = true
}

func (v NullableV2TargetIdentifierAttributesPostRequestDataDefaultValue) IsSet() bool {
	return v.isSet
}

func (v *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2TargetIdentifierAttributesPostRequestDataDefaultValue(val *V2TargetIdentifierAttributesPostRequestDataDefaultValue) *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValue {
	return &NullableV2TargetIdentifierAttributesPostRequestDataDefaultValue{value: val, isSet: true}
}

func (v NullableV2TargetIdentifierAttributesPostRequestDataDefaultValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
