/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf{}

// V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf struct for V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf
type V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf struct {
	Type     string                                                               `json:"type"`
	Template V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate `json:"template"`
}

type _V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf

// NewV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf instantiates a new V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf(type_ string, template V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate) *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf {
	this := V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf{}
	this.Type = type_
	this.Template = template
	return &this
}

// NewV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfWithDefaults instantiates a new V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfWithDefaults() *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf {
	this := V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf{}
	return &this
}

// GetType returns the Type field value
func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) SetType(v string) {
	o.Type = v
}

// GetTemplate returns the Template field value
func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) GetTemplate() V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate {
	if o == nil {
		var ret V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) GetTemplateOk() (*V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) SetTemplate(v V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate) {
	o.Template = v
}

func (o V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["template"] = o.Template
	return toSerialize, nil
}

func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"template",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf := _V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf)

	if err != nil {
		return err
	}

	*o = V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf(varV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf)

	return err
}

type NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf struct {
	value *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf
	isSet bool
}

func (v NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) Get() *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf {
	return v.value
}

func (v *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) Set(val *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf(val *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf {
	return &NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf{value: val, isSet: true}
}

func (v NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
