/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NoteTagsInnerAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NoteTagsInnerAnyOf{}

// NoteTagsInnerAnyOf struct for NoteTagsInnerAnyOf
type NoteTagsInnerAnyOf struct {
	// The type of entity tagged in the note. Can be either 'workspace-member' or 'record'
	Type string `json:"type"`
	// The slug or ID of the object that the tagged record belongs to.
	Object string `json:"object"`
	// The ID of the record that is tagged in the note.
	RecordId string `json:"record_id"`
}

type _NoteTagsInnerAnyOf NoteTagsInnerAnyOf

// NewNoteTagsInnerAnyOf instantiates a new NoteTagsInnerAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNoteTagsInnerAnyOf(type_ string, object string, recordId string) *NoteTagsInnerAnyOf {
	this := NoteTagsInnerAnyOf{}
	this.Type = type_
	this.Object = object
	this.RecordId = recordId
	return &this
}

// NewNoteTagsInnerAnyOfWithDefaults instantiates a new NoteTagsInnerAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNoteTagsInnerAnyOfWithDefaults() *NoteTagsInnerAnyOf {
	this := NoteTagsInnerAnyOf{}
	return &this
}

// GetType returns the Type field value
func (o *NoteTagsInnerAnyOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NoteTagsInnerAnyOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NoteTagsInnerAnyOf) SetType(v string) {
	o.Type = v
}

// GetObject returns the Object field value
func (o *NoteTagsInnerAnyOf) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *NoteTagsInnerAnyOf) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *NoteTagsInnerAnyOf) SetObject(v string) {
	o.Object = v
}

// GetRecordId returns the RecordId field value
func (o *NoteTagsInnerAnyOf) GetRecordId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecordId
}

// GetRecordIdOk returns a tuple with the RecordId field value
// and a boolean to check if the value has been set.
func (o *NoteTagsInnerAnyOf) GetRecordIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordId, true
}

// SetRecordId sets field value
func (o *NoteTagsInnerAnyOf) SetRecordId(v string) {
	o.RecordId = v
}

func (o NoteTagsInnerAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NoteTagsInnerAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["object"] = o.Object
	toSerialize["record_id"] = o.RecordId
	return toSerialize, nil
}

func (o *NoteTagsInnerAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"object",
		"record_id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varNoteTagsInnerAnyOf := _NoteTagsInnerAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNoteTagsInnerAnyOf)

	if err != nil {
		return err
	}

	*o = NoteTagsInnerAnyOf(varNoteTagsInnerAnyOf)

	return err
}

type NullableNoteTagsInnerAnyOf struct {
	value *NoteTagsInnerAnyOf
	isSet bool
}

func (v NullableNoteTagsInnerAnyOf) Get() *NoteTagsInnerAnyOf {
	return v.value
}

func (v *NullableNoteTagsInnerAnyOf) Set(val *NoteTagsInnerAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableNoteTagsInnerAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableNoteTagsInnerAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNoteTagsInnerAnyOf(val *NoteTagsInnerAnyOf) *NullableNoteTagsInnerAnyOf {
	return &NullableNoteTagsInnerAnyOf{value: val, isSet: true}
}

func (v NullableNoteTagsInnerAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNoteTagsInnerAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
