/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ScimV2UsersPost201ResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimV2UsersPost201ResponseMeta{}

// ScimV2UsersPost201ResponseMeta struct for ScimV2UsersPost201ResponseMeta
type ScimV2UsersPost201ResponseMeta struct {
	ResourceType string `json:"resourceType"`
	Created      string `json:"created"`
	LastModified string `json:"lastModified"`
}

type _ScimV2UsersPost201ResponseMeta ScimV2UsersPost201ResponseMeta

// NewScimV2UsersPost201ResponseMeta instantiates a new ScimV2UsersPost201ResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimV2UsersPost201ResponseMeta(resourceType string, created string, lastModified string) *ScimV2UsersPost201ResponseMeta {
	this := ScimV2UsersPost201ResponseMeta{}
	this.ResourceType = resourceType
	this.Created = created
	this.LastModified = lastModified
	return &this
}

// NewScimV2UsersPost201ResponseMetaWithDefaults instantiates a new ScimV2UsersPost201ResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimV2UsersPost201ResponseMetaWithDefaults() *ScimV2UsersPost201ResponseMeta {
	this := ScimV2UsersPost201ResponseMeta{}
	return &this
}

// GetResourceType returns the ResourceType field value
func (o *ScimV2UsersPost201ResponseMeta) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201ResponseMeta) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *ScimV2UsersPost201ResponseMeta) SetResourceType(v string) {
	o.ResourceType = v
}

// GetCreated returns the Created field value
func (o *ScimV2UsersPost201ResponseMeta) GetCreated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201ResponseMeta) GetCreatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *ScimV2UsersPost201ResponseMeta) SetCreated(v string) {
	o.Created = v
}

// GetLastModified returns the LastModified field value
func (o *ScimV2UsersPost201ResponseMeta) GetLastModified() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201ResponseMeta) GetLastModifiedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastModified, true
}

// SetLastModified sets field value
func (o *ScimV2UsersPost201ResponseMeta) SetLastModified(v string) {
	o.LastModified = v
}

func (o ScimV2UsersPost201ResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimV2UsersPost201ResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resourceType"] = o.ResourceType
	toSerialize["created"] = o.Created
	toSerialize["lastModified"] = o.LastModified
	return toSerialize, nil
}

func (o *ScimV2UsersPost201ResponseMeta) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resourceType",
		"created",
		"lastModified",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varScimV2UsersPost201ResponseMeta := _ScimV2UsersPost201ResponseMeta{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScimV2UsersPost201ResponseMeta)

	if err != nil {
		return err
	}

	*o = ScimV2UsersPost201ResponseMeta(varScimV2UsersPost201ResponseMeta)

	return err
}

type NullableScimV2UsersPost201ResponseMeta struct {
	value *ScimV2UsersPost201ResponseMeta
	isSet bool
}

func (v NullableScimV2UsersPost201ResponseMeta) Get() *ScimV2UsersPost201ResponseMeta {
	return v.value
}

func (v *NullableScimV2UsersPost201ResponseMeta) Set(val *ScimV2UsersPost201ResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableScimV2UsersPost201ResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableScimV2UsersPost201ResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimV2UsersPost201ResponseMeta(val *ScimV2UsersPost201ResponseMeta) *NullableScimV2UsersPost201ResponseMeta {
	return &NullableScimV2UsersPost201ResponseMeta{value: val, isSet: true}
}

func (v NullableScimV2UsersPost201ResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimV2UsersPost201ResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
