/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"fmt"
	"os"
)

// V2FilesFileIdGet200ResponseData struct for V2FilesFileIdGet200ResponseData
type V2FilesFileIdGet200ResponseData struct {
	ConnectedFile   *ConnectedFile
	ConnectedFolder *ConnectedFolder
	File            *File
	Folder1         *Folder1
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *V2FilesFileIdGet200ResponseData) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ConnectedFile
	err = json.Unmarshal(data, &dst.ConnectedFile)
	if err == nil {
		jsonConnectedFile, _ := json.Marshal(dst.ConnectedFile)
		if string(jsonConnectedFile) == "{}" { // empty struct
			dst.ConnectedFile = nil
		} else {
			return nil // data stored in dst.ConnectedFile, return on the first match
		}
	} else {
		dst.ConnectedFile = nil
	}

	// try to unmarshal JSON data into ConnectedFolder
	err = json.Unmarshal(data, &dst.ConnectedFolder)
	if err == nil {
		jsonConnectedFolder, _ := json.Marshal(dst.ConnectedFolder)
		if string(jsonConnectedFolder) == "{}" { // empty struct
			dst.ConnectedFolder = nil
		} else {
			return nil // data stored in dst.ConnectedFolder, return on the first match
		}
	} else {
		dst.ConnectedFolder = nil
	}

	// try to unmarshal JSON data into File
	err = json.Unmarshal(data, &dst.File)
	if err == nil {
		jsonFile, _ := json.Marshal(dst.File)
		if string(jsonFile) == "{}" { // empty struct
			dst.File = nil
		} else {
			return nil // data stored in dst.File, return on the first match
		}
	} else {
		dst.File = nil
	}

	// try to unmarshal JSON data into Folder1
	err = json.Unmarshal(data, &dst.Folder1)
	if err == nil {
		jsonFolder1, _ := json.Marshal(dst.Folder1)
		if string(jsonFolder1) == "{}" { // empty struct
			dst.Folder1 = nil
		} else {
			return nil // data stored in dst.Folder1, return on the first match
		}
	} else {
		dst.Folder1 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(V2FilesFileIdGet200ResponseData)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V2FilesFileIdGet200ResponseData) MarshalJSON() ([]byte, error) {
	if src.ConnectedFile != nil {
		return json.Marshal(&src.ConnectedFile)
	}

	if src.ConnectedFolder != nil {
		return json.Marshal(&src.ConnectedFolder)
	}

	if src.File != nil {
		return json.Marshal(&src.File)
	}

	if src.Folder1 != nil {
		return json.Marshal(&src.Folder1)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableV2FilesFileIdGet200ResponseData struct {
	value *V2FilesFileIdGet200ResponseData
	isSet bool
}

func (v NullableV2FilesFileIdGet200ResponseData) Get() *V2FilesFileIdGet200ResponseData {
	return v.value
}

func (v *NullableV2FilesFileIdGet200ResponseData) Set(val *V2FilesFileIdGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV2FilesFileIdGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV2FilesFileIdGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2FilesFileIdGet200ResponseData(val *V2FilesFileIdGet200ResponseData) *NullableV2FilesFileIdGet200ResponseData {
	return &NullableV2FilesFileIdGet200ResponseData{value: val, isSet: true}
}

func (v NullableV2FilesFileIdGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2FilesFileIdGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
