/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1{}

// V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 struct for V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1
type V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 struct {
	Type     string       `json:"type"`
	Template []InputValue `json:"template"`
}

type _V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1

// NewV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 instantiates a new V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1(type_ string, template []InputValue) *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 {
	this := V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1{}
	this.Type = type_
	this.Template = template
	return &this
}

// NewV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1WithDefaults instantiates a new V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1WithDefaults() *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 {
	this := V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1{}
	return &this
}

// GetType returns the Type field value
func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) SetType(v string) {
	o.Type = v
}

// GetTemplate returns the Template field value
func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) GetTemplate() []InputValue {
	if o == nil {
		var ret []InputValue
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) GetTemplateOk() ([]InputValue, bool) {
	if o == nil {
		return nil, false
	}
	return o.Template, true
}

// SetTemplate sets field value
func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) SetTemplate(v []InputValue) {
	o.Template = v
}

func (o V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["template"] = o.Template
	return toSerialize, nil
}

func (o *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"template",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 := _V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1)

	if err != nil {
		return err
	}

	*o = V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1(varV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1)

	return err
}

type NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 struct {
	value *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1
	isSet bool
}

func (v NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) Get() *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 {
	return v.value
}

func (v *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) Set(val *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1(val *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1 {
	return &NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1{value: val, isSet: true}
}

func (v NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
