/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1{}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 struct for V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1
type V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 struct {
	// The point in time at which this value was made \"active\". `active_from` can be considered roughly analogous to `created_at`.
	ActiveFrom time.Time `json:"active_from"`
	// The point in time at which this value was deactivated. If `null`, the value is active.
	ActiveUntil    NullableTime                                                                           `json:"active_until"`
	CreatedByActor V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor `json:"created_by_actor"`
	// A boolean representing whether the checkbox is checked or not. The string values 'true' and 'false' are also accepted.
	Value bool `json:"value"`
	// The attribute type of the value.
	AttributeType string `json:"attribute_type"`
}

type _V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1

// NewV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 instantiates a new V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1(activeFrom time.Time, activeUntil NullableTime, createdByActor V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor, value bool, attributeType string) *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 {
	this := V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1{}
	this.ActiveFrom = activeFrom
	this.ActiveUntil = activeUntil
	this.CreatedByActor = createdByActor
	this.Value = value
	this.AttributeType = attributeType
	return &this
}

// NewV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1WithDefaults instantiates a new V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1WithDefaults() *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 {
	this := V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1{}
	return &this
}

// GetActiveFrom returns the ActiveFrom field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) GetActiveFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ActiveFrom
}

// GetActiveFromOk returns a tuple with the ActiveFrom field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) GetActiveFromOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveFrom, true
}

// SetActiveFrom sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) SetActiveFrom(v time.Time) {
	o.ActiveFrom = v
}

// GetActiveUntil returns the ActiveUntil field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) GetActiveUntil() time.Time {
	if o == nil || o.ActiveUntil.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ActiveUntil.Get()
}

// GetActiveUntilOk returns a tuple with the ActiveUntil field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) GetActiveUntilOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActiveUntil.Get(), o.ActiveUntil.IsSet()
}

// SetActiveUntil sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) SetActiveUntil(v time.Time) {
	o.ActiveUntil.Set(&v)
}

// GetCreatedByActor returns the CreatedByActor field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) GetCreatedByActor() V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor {
	if o == nil {
		var ret V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor
		return ret
	}

	return o.CreatedByActor
}

// GetCreatedByActorOk returns a tuple with the CreatedByActor field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) GetCreatedByActorOk() (*V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedByActor, true
}

// SetCreatedByActor sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) SetCreatedByActor(v V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor) {
	o.CreatedByActor = v
}

// GetValue returns the Value field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) GetValue() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) GetValueOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) SetValue(v bool) {
	o.Value = v
}

// GetAttributeType returns the AttributeType field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) GetAttributeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributeType
}

// GetAttributeTypeOk returns a tuple with the AttributeType field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) GetAttributeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeType, true
}

// SetAttributeType sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) SetAttributeType(v string) {
	o.AttributeType = v
}

func (o V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["active_from"] = o.ActiveFrom
	toSerialize["active_until"] = o.ActiveUntil.Get()
	toSerialize["created_by_actor"] = o.CreatedByActor
	toSerialize["value"] = o.Value
	toSerialize["attribute_type"] = o.AttributeType
	return toSerialize, nil
}

func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"active_from",
		"active_until",
		"created_by_actor",
		"value",
		"attribute_type",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 := _V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1)

	if err != nil {
		return err
	}

	*o = V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1(varV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1)

	return err
}

type NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 struct {
	value *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1
	isSet bool
}

func (v NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) Get() *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 {
	return v.value
}

func (v *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) Set(val *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1(val *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 {
	return &NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1{value: val, isSet: true}
}

func (v NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
