/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ScimV2GroupsPost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimV2GroupsPost201Response{}

// ScimV2GroupsPost201Response Created
type ScimV2GroupsPost201Response struct {
	Schemas     []string                                  `json:"schemas"`
	Id          string                                    `json:"id"`
	DisplayName string                                    `json:"displayName"`
	Members     []ScimV2GroupsPost201ResponseMembersInner `json:"members"`
	Meta        ScimV2UsersPost201ResponseMeta            `json:"meta"`
}

type _ScimV2GroupsPost201Response ScimV2GroupsPost201Response

// NewScimV2GroupsPost201Response instantiates a new ScimV2GroupsPost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimV2GroupsPost201Response(schemas []string, id string, displayName string, members []ScimV2GroupsPost201ResponseMembersInner, meta ScimV2UsersPost201ResponseMeta) *ScimV2GroupsPost201Response {
	this := ScimV2GroupsPost201Response{}
	this.Schemas = schemas
	this.Id = id
	this.DisplayName = displayName
	this.Members = members
	this.Meta = meta
	return &this
}

// NewScimV2GroupsPost201ResponseWithDefaults instantiates a new ScimV2GroupsPost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimV2GroupsPost201ResponseWithDefaults() *ScimV2GroupsPost201Response {
	this := ScimV2GroupsPost201Response{}
	return &this
}

// GetSchemas returns the Schemas field value
func (o *ScimV2GroupsPost201Response) GetSchemas() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value
// and a boolean to check if the value has been set.
func (o *ScimV2GroupsPost201Response) GetSchemasOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Schemas, true
}

// SetSchemas sets field value
func (o *ScimV2GroupsPost201Response) SetSchemas(v []string) {
	o.Schemas = v
}

// GetId returns the Id field value
func (o *ScimV2GroupsPost201Response) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ScimV2GroupsPost201Response) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ScimV2GroupsPost201Response) SetId(v string) {
	o.Id = v
}

// GetDisplayName returns the DisplayName field value
func (o *ScimV2GroupsPost201Response) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ScimV2GroupsPost201Response) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ScimV2GroupsPost201Response) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetMembers returns the Members field value
func (o *ScimV2GroupsPost201Response) GetMembers() []ScimV2GroupsPost201ResponseMembersInner {
	if o == nil {
		var ret []ScimV2GroupsPost201ResponseMembersInner
		return ret
	}

	return o.Members
}

// GetMembersOk returns a tuple with the Members field value
// and a boolean to check if the value has been set.
func (o *ScimV2GroupsPost201Response) GetMembersOk() ([]ScimV2GroupsPost201ResponseMembersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Members, true
}

// SetMembers sets field value
func (o *ScimV2GroupsPost201Response) SetMembers(v []ScimV2GroupsPost201ResponseMembersInner) {
	o.Members = v
}

// GetMeta returns the Meta field value
func (o *ScimV2GroupsPost201Response) GetMeta() ScimV2UsersPost201ResponseMeta {
	if o == nil {
		var ret ScimV2UsersPost201ResponseMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *ScimV2GroupsPost201Response) GetMetaOk() (*ScimV2UsersPost201ResponseMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *ScimV2GroupsPost201Response) SetMeta(v ScimV2UsersPost201ResponseMeta) {
	o.Meta = v
}

func (o ScimV2GroupsPost201Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimV2GroupsPost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schemas"] = o.Schemas
	toSerialize["id"] = o.Id
	toSerialize["displayName"] = o.DisplayName
	toSerialize["members"] = o.Members
	toSerialize["meta"] = o.Meta
	return toSerialize, nil
}

func (o *ScimV2GroupsPost201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schemas",
		"id",
		"displayName",
		"members",
		"meta",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varScimV2GroupsPost201Response := _ScimV2GroupsPost201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScimV2GroupsPost201Response)

	if err != nil {
		return err
	}

	*o = ScimV2GroupsPost201Response(varScimV2GroupsPost201Response)

	return err
}

type NullableScimV2GroupsPost201Response struct {
	value *ScimV2GroupsPost201Response
	isSet bool
}

func (v NullableScimV2GroupsPost201Response) Get() *ScimV2GroupsPost201Response {
	return v.value
}

func (v *NullableScimV2GroupsPost201Response) Set(val *ScimV2GroupsPost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableScimV2GroupsPost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableScimV2GroupsPost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimV2GroupsPost201Response(val *ScimV2GroupsPost201Response) *NullableScimV2GroupsPost201Response {
	return &NullableScimV2GroupsPost201Response{value: val, isSet: true}
}

func (v NullableScimV2GroupsPost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimV2GroupsPost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
