/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"fmt"
)

// V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate struct for V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate
type V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate struct {
	value *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate
	isSet bool
}

func (v NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate) Get() *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate {
	return v.value
}

func (v *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate) Set(val *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate(val *V2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate) *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate {
	return &NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate{value: val, isSet: true}
}

func (v NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2TargetIdentifierAttributesPostRequestDataDefaultValueAnyOfTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
