/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ScimV2UsersPost201ResponseName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimV2UsersPost201ResponseName{}

// ScimV2UsersPost201ResponseName struct for ScimV2UsersPost201ResponseName
type ScimV2UsersPost201ResponseName struct {
	GivenName  string `json:"givenName"`
	FamilyName string `json:"familyName"`
}

type _ScimV2UsersPost201ResponseName ScimV2UsersPost201ResponseName

// NewScimV2UsersPost201ResponseName instantiates a new ScimV2UsersPost201ResponseName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimV2UsersPost201ResponseName(givenName string, familyName string) *ScimV2UsersPost201ResponseName {
	this := ScimV2UsersPost201ResponseName{}
	this.GivenName = givenName
	this.FamilyName = familyName
	return &this
}

// NewScimV2UsersPost201ResponseNameWithDefaults instantiates a new ScimV2UsersPost201ResponseName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimV2UsersPost201ResponseNameWithDefaults() *ScimV2UsersPost201ResponseName {
	this := ScimV2UsersPost201ResponseName{}
	return &this
}

// GetGivenName returns the GivenName field value
func (o *ScimV2UsersPost201ResponseName) GetGivenName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GivenName
}

// GetGivenNameOk returns a tuple with the GivenName field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201ResponseName) GetGivenNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GivenName, true
}

// SetGivenName sets field value
func (o *ScimV2UsersPost201ResponseName) SetGivenName(v string) {
	o.GivenName = v
}

// GetFamilyName returns the FamilyName field value
func (o *ScimV2UsersPost201ResponseName) GetFamilyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FamilyName
}

// GetFamilyNameOk returns a tuple with the FamilyName field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201ResponseName) GetFamilyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FamilyName, true
}

// SetFamilyName sets field value
func (o *ScimV2UsersPost201ResponseName) SetFamilyName(v string) {
	o.FamilyName = v
}

func (o ScimV2UsersPost201ResponseName) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimV2UsersPost201ResponseName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["givenName"] = o.GivenName
	toSerialize["familyName"] = o.FamilyName
	return toSerialize, nil
}

func (o *ScimV2UsersPost201ResponseName) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"givenName",
		"familyName",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varScimV2UsersPost201ResponseName := _ScimV2UsersPost201ResponseName{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScimV2UsersPost201ResponseName)

	if err != nil {
		return err
	}

	*o = ScimV2UsersPost201ResponseName(varScimV2UsersPost201ResponseName)

	return err
}

type NullableScimV2UsersPost201ResponseName struct {
	value *ScimV2UsersPost201ResponseName
	isSet bool
}

func (v NullableScimV2UsersPost201ResponseName) Get() *ScimV2UsersPost201ResponseName {
	return v.value
}

func (v *NullableScimV2UsersPost201ResponseName) Set(val *ScimV2UsersPost201ResponseName) {
	v.value = val
	v.isSet = true
}

func (v NullableScimV2UsersPost201ResponseName) IsSet() bool {
	return v.isSet
}

func (v *NullableScimV2UsersPost201ResponseName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimV2UsersPost201ResponseName(val *ScimV2UsersPost201ResponseName) *NullableScimV2UsersPost201ResponseName {
	return &NullableScimV2UsersPost201ResponseName{value: val, isSet: true}
}

func (v NullableScimV2UsersPost201ResponseName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimV2UsersPost201ResponseName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
