/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"fmt"
)

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner struct for V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner
type V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner struct {
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf              *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1             *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10            *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11            *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12            *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13            *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2             *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3             *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4             *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5             *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6             *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7             *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8             *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8
	V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9             *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11 *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5  *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9  *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9)
	if err == nil {
		jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9, _ := json.Marshal(dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9)
		if string(jsonV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner) MarshalJSON() ([]byte, error) {
	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf1)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf10)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf11)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf12)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf13)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf2)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf3)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf4)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf5)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf7)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf8)
	}

	if src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf9)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInner struct {
	value *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner
	isSet bool
}

func (v NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInner) Get() *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner {
	return v.value
}

func (v *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInner) Set(val *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInner(val *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInner) *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInner {
	return &NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInner{value: val, isSet: true}
}

func (v NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
