/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ScimV2GroupsPost201ResponseMembersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimV2GroupsPost201ResponseMembersInner{}

// ScimV2GroupsPost201ResponseMembersInner struct for ScimV2GroupsPost201ResponseMembersInner
type ScimV2GroupsPost201ResponseMembersInner struct {
	Value   string  `json:"value"`
	Ref     string  `json:"$ref"`
	Display *string `json:"display,omitempty"`
}

type _ScimV2GroupsPost201ResponseMembersInner ScimV2GroupsPost201ResponseMembersInner

// NewScimV2GroupsPost201ResponseMembersInner instantiates a new ScimV2GroupsPost201ResponseMembersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimV2GroupsPost201ResponseMembersInner(value string, ref string) *ScimV2GroupsPost201ResponseMembersInner {
	this := ScimV2GroupsPost201ResponseMembersInner{}
	this.Value = value
	this.Ref = ref
	return &this
}

// NewScimV2GroupsPost201ResponseMembersInnerWithDefaults instantiates a new ScimV2GroupsPost201ResponseMembersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimV2GroupsPost201ResponseMembersInnerWithDefaults() *ScimV2GroupsPost201ResponseMembersInner {
	this := ScimV2GroupsPost201ResponseMembersInner{}
	return &this
}

// GetValue returns the Value field value
func (o *ScimV2GroupsPost201ResponseMembersInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ScimV2GroupsPost201ResponseMembersInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ScimV2GroupsPost201ResponseMembersInner) SetValue(v string) {
	o.Value = v
}

// GetRef returns the Ref field value
func (o *ScimV2GroupsPost201ResponseMembersInner) GetRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ref
}

// GetRefOk returns a tuple with the Ref field value
// and a boolean to check if the value has been set.
func (o *ScimV2GroupsPost201ResponseMembersInner) GetRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ref, true
}

// SetRef sets field value
func (o *ScimV2GroupsPost201ResponseMembersInner) SetRef(v string) {
	o.Ref = v
}

// GetDisplay returns the Display field value if set, zero value otherwise.
func (o *ScimV2GroupsPost201ResponseMembersInner) GetDisplay() string {
	if o == nil || IsNil(o.Display) {
		var ret string
		return ret
	}
	return *o.Display
}

// GetDisplayOk returns a tuple with the Display field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimV2GroupsPost201ResponseMembersInner) GetDisplayOk() (*string, bool) {
	if o == nil || IsNil(o.Display) {
		return nil, false
	}
	return o.Display, true
}

// HasDisplay returns a boolean if a field has been set.
func (o *ScimV2GroupsPost201ResponseMembersInner) HasDisplay() bool {
	if o != nil && !IsNil(o.Display) {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given string and assigns it to the Display field.
func (o *ScimV2GroupsPost201ResponseMembersInner) SetDisplay(v string) {
	o.Display = &v
}

func (o ScimV2GroupsPost201ResponseMembersInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimV2GroupsPost201ResponseMembersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["$ref"] = o.Ref
	if !IsNil(o.Display) {
		toSerialize["display"] = o.Display
	}
	return toSerialize, nil
}

func (o *ScimV2GroupsPost201ResponseMembersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"$ref",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varScimV2GroupsPost201ResponseMembersInner := _ScimV2GroupsPost201ResponseMembersInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScimV2GroupsPost201ResponseMembersInner)

	if err != nil {
		return err
	}

	*o = ScimV2GroupsPost201ResponseMembersInner(varScimV2GroupsPost201ResponseMembersInner)

	return err
}

type NullableScimV2GroupsPost201ResponseMembersInner struct {
	value *ScimV2GroupsPost201ResponseMembersInner
	isSet bool
}

func (v NullableScimV2GroupsPost201ResponseMembersInner) Get() *ScimV2GroupsPost201ResponseMembersInner {
	return v.value
}

func (v *NullableScimV2GroupsPost201ResponseMembersInner) Set(val *ScimV2GroupsPost201ResponseMembersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableScimV2GroupsPost201ResponseMembersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableScimV2GroupsPost201ResponseMembersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimV2GroupsPost201ResponseMembersInner(val *ScimV2GroupsPost201ResponseMembersInner) *NullableScimV2GroupsPost201ResponseMembersInner {
	return &NullableScimV2GroupsPost201ResponseMembersInner{value: val, isSet: true}
}

func (v NullableScimV2GroupsPost201ResponseMembersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimV2GroupsPost201ResponseMembersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
