/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InputValueAnyOf11 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputValueAnyOf11{}

// InputValueAnyOf11 struct for InputValueAnyOf11
type InputValueAnyOf11 struct {
	// The UUID or select option title identifying the selected select option.
	Option string `json:"option"`
}

type _InputValueAnyOf11 InputValueAnyOf11

// NewInputValueAnyOf11 instantiates a new InputValueAnyOf11 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputValueAnyOf11(option string) *InputValueAnyOf11 {
	this := InputValueAnyOf11{}
	this.Option = option
	return &this
}

// NewInputValueAnyOf11WithDefaults instantiates a new InputValueAnyOf11 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputValueAnyOf11WithDefaults() *InputValueAnyOf11 {
	this := InputValueAnyOf11{}
	return &this
}

// GetOption returns the Option field value
func (o *InputValueAnyOf11) GetOption() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Option
}

// GetOptionOk returns a tuple with the Option field value
// and a boolean to check if the value has been set.
func (o *InputValueAnyOf11) GetOptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Option, true
}

// SetOption sets field value
func (o *InputValueAnyOf11) SetOption(v string) {
	o.Option = v
}

func (o InputValueAnyOf11) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputValueAnyOf11) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["option"] = o.Option
	return toSerialize, nil
}

func (o *InputValueAnyOf11) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"option",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varInputValueAnyOf11 := _InputValueAnyOf11{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputValueAnyOf11)

	if err != nil {
		return err
	}

	*o = InputValueAnyOf11(varInputValueAnyOf11)

	return err
}

type NullableInputValueAnyOf11 struct {
	value *InputValueAnyOf11
	isSet bool
}

func (v NullableInputValueAnyOf11) Get() *InputValueAnyOf11 {
	return v.value
}

func (v *NullableInputValueAnyOf11) Set(val *InputValueAnyOf11) {
	v.value = val
	v.isSet = true
}

func (v NullableInputValueAnyOf11) IsSet() bool {
	return v.isSet
}

func (v *NullableInputValueAnyOf11) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputValueAnyOf11(val *InputValueAnyOf11) *NullableInputValueAnyOf11 {
	return &NullableInputValueAnyOf11{value: val, isSet: true}
}

func (v NullableInputValueAnyOf11) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputValueAnyOf11) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
