/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ScimV2UsersPost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimV2UsersPost201Response{}

// ScimV2UsersPost201Response Created
type ScimV2UsersPost201Response struct {
	Schemas    []string                                `json:"schemas"`
	Id         string                                  `json:"id"`
	UserName   string                                  `json:"userName"`
	Name       ScimV2UsersPost201ResponseName          `json:"name"`
	Emails     []ScimV2UsersPost201ResponseEmailsInner `json:"emails"`
	Roles      []ScimV2UsersPost201ResponseRolesInner  `json:"roles"`
	ProfileUrl *string                                 `json:"profileUrl,omitempty"`
	Active     bool                                    `json:"active"`
	Meta       ScimV2UsersPost201ResponseMeta          `json:"meta"`
}

type _ScimV2UsersPost201Response ScimV2UsersPost201Response

// NewScimV2UsersPost201Response instantiates a new ScimV2UsersPost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimV2UsersPost201Response(schemas []string, id string, userName string, name ScimV2UsersPost201ResponseName, emails []ScimV2UsersPost201ResponseEmailsInner, roles []ScimV2UsersPost201ResponseRolesInner, active bool, meta ScimV2UsersPost201ResponseMeta) *ScimV2UsersPost201Response {
	this := ScimV2UsersPost201Response{}
	this.Schemas = schemas
	this.Id = id
	this.UserName = userName
	this.Name = name
	this.Emails = emails
	this.Roles = roles
	this.Active = active
	this.Meta = meta
	return &this
}

// NewScimV2UsersPost201ResponseWithDefaults instantiates a new ScimV2UsersPost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimV2UsersPost201ResponseWithDefaults() *ScimV2UsersPost201Response {
	this := ScimV2UsersPost201Response{}
	return &this
}

// GetSchemas returns the Schemas field value
func (o *ScimV2UsersPost201Response) GetSchemas() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201Response) GetSchemasOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Schemas, true
}

// SetSchemas sets field value
func (o *ScimV2UsersPost201Response) SetSchemas(v []string) {
	o.Schemas = v
}

// GetId returns the Id field value
func (o *ScimV2UsersPost201Response) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201Response) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ScimV2UsersPost201Response) SetId(v string) {
	o.Id = v
}

// GetUserName returns the UserName field value
func (o *ScimV2UsersPost201Response) GetUserName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201Response) GetUserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserName, true
}

// SetUserName sets field value
func (o *ScimV2UsersPost201Response) SetUserName(v string) {
	o.UserName = v
}

// GetName returns the Name field value
func (o *ScimV2UsersPost201Response) GetName() ScimV2UsersPost201ResponseName {
	if o == nil {
		var ret ScimV2UsersPost201ResponseName
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201Response) GetNameOk() (*ScimV2UsersPost201ResponseName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ScimV2UsersPost201Response) SetName(v ScimV2UsersPost201ResponseName) {
	o.Name = v
}

// GetEmails returns the Emails field value
func (o *ScimV2UsersPost201Response) GetEmails() []ScimV2UsersPost201ResponseEmailsInner {
	if o == nil {
		var ret []ScimV2UsersPost201ResponseEmailsInner
		return ret
	}

	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201Response) GetEmailsOk() ([]ScimV2UsersPost201ResponseEmailsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Emails, true
}

// SetEmails sets field value
func (o *ScimV2UsersPost201Response) SetEmails(v []ScimV2UsersPost201ResponseEmailsInner) {
	o.Emails = v
}

// GetRoles returns the Roles field value
func (o *ScimV2UsersPost201Response) GetRoles() []ScimV2UsersPost201ResponseRolesInner {
	if o == nil {
		var ret []ScimV2UsersPost201ResponseRolesInner
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201Response) GetRolesOk() ([]ScimV2UsersPost201ResponseRolesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles, true
}

// SetRoles sets field value
func (o *ScimV2UsersPost201Response) SetRoles(v []ScimV2UsersPost201ResponseRolesInner) {
	o.Roles = v
}

// GetProfileUrl returns the ProfileUrl field value if set, zero value otherwise.
func (o *ScimV2UsersPost201Response) GetProfileUrl() string {
	if o == nil || IsNil(o.ProfileUrl) {
		var ret string
		return ret
	}
	return *o.ProfileUrl
}

// GetProfileUrlOk returns a tuple with the ProfileUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201Response) GetProfileUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ProfileUrl) {
		return nil, false
	}
	return o.ProfileUrl, true
}

// HasProfileUrl returns a boolean if a field has been set.
func (o *ScimV2UsersPost201Response) HasProfileUrl() bool {
	if o != nil && !IsNil(o.ProfileUrl) {
		return true
	}

	return false
}

// SetProfileUrl gets a reference to the given string and assigns it to the ProfileUrl field.
func (o *ScimV2UsersPost201Response) SetProfileUrl(v string) {
	o.ProfileUrl = &v
}

// GetActive returns the Active field value
func (o *ScimV2UsersPost201Response) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201Response) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *ScimV2UsersPost201Response) SetActive(v bool) {
	o.Active = v
}

// GetMeta returns the Meta field value
func (o *ScimV2UsersPost201Response) GetMeta() ScimV2UsersPost201ResponseMeta {
	if o == nil {
		var ret ScimV2UsersPost201ResponseMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201Response) GetMetaOk() (*ScimV2UsersPost201ResponseMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *ScimV2UsersPost201Response) SetMeta(v ScimV2UsersPost201ResponseMeta) {
	o.Meta = v
}

func (o ScimV2UsersPost201Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimV2UsersPost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schemas"] = o.Schemas
	toSerialize["id"] = o.Id
	toSerialize["userName"] = o.UserName
	toSerialize["name"] = o.Name
	toSerialize["emails"] = o.Emails
	toSerialize["roles"] = o.Roles
	if !IsNil(o.ProfileUrl) {
		toSerialize["profileUrl"] = o.ProfileUrl
	}
	toSerialize["active"] = o.Active
	toSerialize["meta"] = o.Meta
	return toSerialize, nil
}

func (o *ScimV2UsersPost201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schemas",
		"id",
		"userName",
		"name",
		"emails",
		"roles",
		"active",
		"meta",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varScimV2UsersPost201Response := _ScimV2UsersPost201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScimV2UsersPost201Response)

	if err != nil {
		return err
	}

	*o = ScimV2UsersPost201Response(varScimV2UsersPost201Response)

	return err
}

type NullableScimV2UsersPost201Response struct {
	value *ScimV2UsersPost201Response
	isSet bool
}

func (v NullableScimV2UsersPost201Response) Get() *ScimV2UsersPost201Response {
	return v.value
}

func (v *NullableScimV2UsersPost201Response) Set(val *ScimV2UsersPost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableScimV2UsersPost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableScimV2UsersPost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimV2UsersPost201Response(val *ScimV2UsersPost201Response) *NullableScimV2UsersPost201Response {
	return &NullableScimV2UsersPost201Response{value: val, isSet: true}
}

func (v NullableScimV2UsersPost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimV2UsersPost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
