/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6{}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 struct for V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6
type V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 struct {
	// The point in time at which this value was made \"active\". `active_from` can be considered roughly analogous to `created_at`.
	ActiveFrom time.Time `json:"active_from"`
	// The point in time at which this value was deactivated. If `null`, the value is active.
	ActiveUntil    NullableTime                                                                           `json:"active_until"`
	CreatedByActor V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor `json:"created_by_actor"`
	// The type of interaction e.g. calendar or email.
	InteractionType string `json:"interaction_type"`
	// When the interaction occurred.
	InteractedAt time.Time                                                                              `json:"interacted_at"`
	OwnerActor   V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor `json:"owner_actor"`
	// The attribute type of the value.
	AttributeType string `json:"attribute_type"`
}

type _V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6

// NewV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 instantiates a new V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6(activeFrom time.Time, activeUntil NullableTime, createdByActor V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor, interactionType string, interactedAt time.Time, ownerActor V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor, attributeType string) *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 {
	this := V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6{}
	this.ActiveFrom = activeFrom
	this.ActiveUntil = activeUntil
	this.CreatedByActor = createdByActor
	this.InteractionType = interactionType
	this.InteractedAt = interactedAt
	this.OwnerActor = ownerActor
	this.AttributeType = attributeType
	return &this
}

// NewV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6WithDefaults instantiates a new V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6WithDefaults() *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 {
	this := V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6{}
	return &this
}

// GetActiveFrom returns the ActiveFrom field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetActiveFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ActiveFrom
}

// GetActiveFromOk returns a tuple with the ActiveFrom field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetActiveFromOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveFrom, true
}

// SetActiveFrom sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) SetActiveFrom(v time.Time) {
	o.ActiveFrom = v
}

// GetActiveUntil returns the ActiveUntil field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetActiveUntil() time.Time {
	if o == nil || o.ActiveUntil.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ActiveUntil.Get()
}

// GetActiveUntilOk returns a tuple with the ActiveUntil field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetActiveUntilOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActiveUntil.Get(), o.ActiveUntil.IsSet()
}

// SetActiveUntil sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) SetActiveUntil(v time.Time) {
	o.ActiveUntil.Set(&v)
}

// GetCreatedByActor returns the CreatedByActor field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetCreatedByActor() V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor {
	if o == nil {
		var ret V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor
		return ret
	}

	return o.CreatedByActor
}

// GetCreatedByActorOk returns a tuple with the CreatedByActor field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetCreatedByActorOk() (*V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedByActor, true
}

// SetCreatedByActor sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) SetCreatedByActor(v V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor) {
	o.CreatedByActor = v
}

// GetInteractionType returns the InteractionType field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetInteractionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InteractionType
}

// GetInteractionTypeOk returns a tuple with the InteractionType field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetInteractionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InteractionType, true
}

// SetInteractionType sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) SetInteractionType(v string) {
	o.InteractionType = v
}

// GetInteractedAt returns the InteractedAt field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetInteractedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.InteractedAt
}

// GetInteractedAtOk returns a tuple with the InteractedAt field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetInteractedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InteractedAt, true
}

// SetInteractedAt sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) SetInteractedAt(v time.Time) {
	o.InteractedAt = v
}

// GetOwnerActor returns the OwnerActor field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetOwnerActor() V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor {
	if o == nil {
		var ret V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor
		return ret
	}

	return o.OwnerActor
}

// GetOwnerActorOk returns a tuple with the OwnerActor field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetOwnerActorOk() (*V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerActor, true
}

// SetOwnerActor sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) SetOwnerActor(v V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor) {
	o.OwnerActor = v
}

// GetAttributeType returns the AttributeType field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetAttributeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributeType
}

// GetAttributeTypeOk returns a tuple with the AttributeType field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) GetAttributeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeType, true
}

// SetAttributeType sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) SetAttributeType(v string) {
	o.AttributeType = v
}

func (o V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["active_from"] = o.ActiveFrom
	toSerialize["active_until"] = o.ActiveUntil.Get()
	toSerialize["created_by_actor"] = o.CreatedByActor
	toSerialize["interaction_type"] = o.InteractionType
	toSerialize["interacted_at"] = o.InteractedAt
	toSerialize["owner_actor"] = o.OwnerActor
	toSerialize["attribute_type"] = o.AttributeType
	return toSerialize, nil
}

func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"active_from",
		"active_until",
		"created_by_actor",
		"interaction_type",
		"interacted_at",
		"owner_actor",
		"attribute_type",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 := _V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6)

	if err != nil {
		return err
	}

	*o = V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6(varV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6)

	return err
}

type NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 struct {
	value *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6
	isSet bool
}

func (v NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) Get() *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 {
	return v.value
}

func (v *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) Set(val *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6(val *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6 {
	return &NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6{value: val, isSet: true}
}

func (v NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf6) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
