/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"fmt"
)

// checks if the V2FilesGet200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2FilesGet200ResponseDataInner{}

// V2FilesGet200ResponseDataInner struct for V2FilesGet200ResponseDataInner
type V2FilesGet200ResponseDataInner struct {
	ConnectedFile   *ConnectedFile
	ConnectedFolder *ConnectedFolder
	File            *File
	Folder          *Folder
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *V2FilesGet200ResponseDataInner) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = json.Unmarshal(data, &jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'connected-file'
	if jsonDict["file_type"] == "connected-file" {
		// try to unmarshal JSON data into ConnectedFile
		err = json.Unmarshal(data, &dst.ConnectedFile)
		if err == nil {
			jsonConnectedFile, _ := json.Marshal(dst.ConnectedFile)
			if string(jsonConnectedFile) == "{}" { // empty struct
				dst.ConnectedFile = nil
			} else {
				return nil // data stored in dst.ConnectedFile, return on the first match
			}
		} else {
			dst.ConnectedFile = nil
		}
	}

	// check if the discriminator value is 'connected-folder'
	if jsonDict["file_type"] == "connected-folder" {
		// try to unmarshal JSON data into ConnectedFolder
		err = json.Unmarshal(data, &dst.ConnectedFolder)
		if err == nil {
			jsonConnectedFolder, _ := json.Marshal(dst.ConnectedFolder)
			if string(jsonConnectedFolder) == "{}" { // empty struct
				dst.ConnectedFolder = nil
			} else {
				return nil // data stored in dst.ConnectedFolder, return on the first match
			}
		} else {
			dst.ConnectedFolder = nil
		}
	}

	// check if the discriminator value is 'file'
	if jsonDict["file_type"] == "file" {
		// try to unmarshal JSON data into File
		err = json.Unmarshal(data, &dst.File)
		if err == nil {
			jsonFile, _ := json.Marshal(dst.File)
			if string(jsonFile) == "{}" { // empty struct
				dst.File = nil
			} else {
				return nil // data stored in dst.File, return on the first match
			}
		} else {
			dst.File = nil
		}
	}

	// check if the discriminator value is 'folder'
	if jsonDict["file_type"] == "folder" {
		// try to unmarshal JSON data into Folder
		err = json.Unmarshal(data, &dst.Folder)
		if err == nil {
			jsonFolder, _ := json.Marshal(dst.Folder)
			if string(jsonFolder) == "{}" { // empty struct
				dst.Folder = nil
			} else {
				return nil // data stored in dst.Folder, return on the first match
			}
		} else {
			dst.Folder = nil
		}
	}

	// try to unmarshal JSON data into ConnectedFile
	err = json.Unmarshal(data, &dst.ConnectedFile)
	if err == nil {
		jsonConnectedFile, _ := json.Marshal(dst.ConnectedFile)
		if string(jsonConnectedFile) == "{}" { // empty struct
			dst.ConnectedFile = nil
		} else {
			return nil // data stored in dst.ConnectedFile, return on the first match
		}
	} else {
		dst.ConnectedFile = nil
	}

	// try to unmarshal JSON data into ConnectedFolder
	err = json.Unmarshal(data, &dst.ConnectedFolder)
	if err == nil {
		jsonConnectedFolder, _ := json.Marshal(dst.ConnectedFolder)
		if string(jsonConnectedFolder) == "{}" { // empty struct
			dst.ConnectedFolder = nil
		} else {
			return nil // data stored in dst.ConnectedFolder, return on the first match
		}
	} else {
		dst.ConnectedFolder = nil
	}

	// try to unmarshal JSON data into File
	err = json.Unmarshal(data, &dst.File)
	if err == nil {
		jsonFile, _ := json.Marshal(dst.File)
		if string(jsonFile) == "{}" { // empty struct
			dst.File = nil
		} else {
			return nil // data stored in dst.File, return on the first match
		}
	} else {
		dst.File = nil
	}

	// try to unmarshal JSON data into Folder
	err = json.Unmarshal(data, &dst.Folder)
	if err == nil {
		jsonFolder, _ := json.Marshal(dst.Folder)
		if string(jsonFolder) == "{}" { // empty struct
			dst.Folder = nil
		} else {
			return nil // data stored in dst.Folder, return on the first match
		}
	} else {
		dst.Folder = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(V2FilesGet200ResponseDataInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V2FilesGet200ResponseDataInner) MarshalJSON() ([]byte, error) {
	if src.ConnectedFile != nil {
		return json.Marshal(&src.ConnectedFile)
	}

	if src.ConnectedFolder != nil {
		return json.Marshal(&src.ConnectedFolder)
	}

	if src.File != nil {
		return json.Marshal(&src.File)
	}

	if src.Folder != nil {
		return json.Marshal(&src.Folder)
	}

	return nil, nil // no data in anyOf schemas
}

func (src V2FilesGet200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	if src.ConnectedFile != nil {
		return src.ConnectedFile.ToMap()
	}

	if src.ConnectedFolder != nil {
		return src.ConnectedFolder.ToMap()
	}

	if src.File != nil {
		return src.File.ToMap()
	}

	if src.Folder != nil {
		return src.Folder.ToMap()
	}

	return nil, nil // no data in anyOf schemas
}

type NullableV2FilesGet200ResponseDataInner struct {
	value *V2FilesGet200ResponseDataInner
	isSet bool
}

func (v NullableV2FilesGet200ResponseDataInner) Get() *V2FilesGet200ResponseDataInner {
	return v.value
}

func (v *NullableV2FilesGet200ResponseDataInner) Set(val *V2FilesGet200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV2FilesGet200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV2FilesGet200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2FilesGet200ResponseDataInner(val *V2FilesGet200ResponseDataInner) *NullableV2FilesGet200ResponseDataInner {
	return &NullableV2FilesGet200ResponseDataInner{value: val, isSet: true}
}

func (v NullableV2FilesGet200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2FilesGet200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
