/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ScimV2UsersPost201ResponseEmailsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimV2UsersPost201ResponseEmailsInner{}

// ScimV2UsersPost201ResponseEmailsInner struct for ScimV2UsersPost201ResponseEmailsInner
type ScimV2UsersPost201ResponseEmailsInner struct {
	Value   string  `json:"value"`
	Primary bool    `json:"primary"`
	Type    *string `json:"type,omitempty"`
}

type _ScimV2UsersPost201ResponseEmailsInner ScimV2UsersPost201ResponseEmailsInner

// NewScimV2UsersPost201ResponseEmailsInner instantiates a new ScimV2UsersPost201ResponseEmailsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimV2UsersPost201ResponseEmailsInner(value string, primary bool) *ScimV2UsersPost201ResponseEmailsInner {
	this := ScimV2UsersPost201ResponseEmailsInner{}
	this.Value = value
	this.Primary = primary
	return &this
}

// NewScimV2UsersPost201ResponseEmailsInnerWithDefaults instantiates a new ScimV2UsersPost201ResponseEmailsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimV2UsersPost201ResponseEmailsInnerWithDefaults() *ScimV2UsersPost201ResponseEmailsInner {
	this := ScimV2UsersPost201ResponseEmailsInner{}
	return &this
}

// GetValue returns the Value field value
func (o *ScimV2UsersPost201ResponseEmailsInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201ResponseEmailsInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ScimV2UsersPost201ResponseEmailsInner) SetValue(v string) {
	o.Value = v
}

// GetPrimary returns the Primary field value
func (o *ScimV2UsersPost201ResponseEmailsInner) GetPrimary() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Primary
}

// GetPrimaryOk returns a tuple with the Primary field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201ResponseEmailsInner) GetPrimaryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Primary, true
}

// SetPrimary sets field value
func (o *ScimV2UsersPost201ResponseEmailsInner) SetPrimary(v bool) {
	o.Primary = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ScimV2UsersPost201ResponseEmailsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201ResponseEmailsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ScimV2UsersPost201ResponseEmailsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ScimV2UsersPost201ResponseEmailsInner) SetType(v string) {
	o.Type = &v
}

func (o ScimV2UsersPost201ResponseEmailsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimV2UsersPost201ResponseEmailsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["primary"] = o.Primary
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *ScimV2UsersPost201ResponseEmailsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"primary",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varScimV2UsersPost201ResponseEmailsInner := _ScimV2UsersPost201ResponseEmailsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScimV2UsersPost201ResponseEmailsInner)

	if err != nil {
		return err
	}

	*o = ScimV2UsersPost201ResponseEmailsInner(varScimV2UsersPost201ResponseEmailsInner)

	return err
}

type NullableScimV2UsersPost201ResponseEmailsInner struct {
	value *ScimV2UsersPost201ResponseEmailsInner
	isSet bool
}

func (v NullableScimV2UsersPost201ResponseEmailsInner) Get() *ScimV2UsersPost201ResponseEmailsInner {
	return v.value
}

func (v *NullableScimV2UsersPost201ResponseEmailsInner) Set(val *ScimV2UsersPost201ResponseEmailsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableScimV2UsersPost201ResponseEmailsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableScimV2UsersPost201ResponseEmailsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimV2UsersPost201ResponseEmailsInner(val *ScimV2UsersPost201ResponseEmailsInner) *NullableScimV2UsersPost201ResponseEmailsInner {
	return &NullableScimV2UsersPost201ResponseEmailsInner{value: val, isSet: true}
}

func (v NullableScimV2UsersPost201ResponseEmailsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimV2UsersPost201ResponseEmailsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
