/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"fmt"
)

// V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner struct for V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner
type V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner struct {
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf   *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf1  *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf1
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf10 *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf10
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11 *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf12 *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf12
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf13 *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf13
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf14 *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf14
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf15 *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf15
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf16 *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf16
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf2  *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf2
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf3  *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf3
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf4  *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf4
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5  *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf6  *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf6
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf7  *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf7
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf8  *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf8
	V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9  *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf1
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf1)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf1, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf1)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf1) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf1 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf1, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf1 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf10
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf10)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf10, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf10)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf10) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf10 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf10, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf10 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf12
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf12)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf12, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf12)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf12) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf12 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf12, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf12 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf13
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf13)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf13, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf13)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf13) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf13 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf13, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf13 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf14
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf14)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf14, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf14)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf14) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf14 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf14, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf14 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf15
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf15)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf15, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf15)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf15) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf15 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf15, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf15 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf16
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf16)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf16, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf16)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf16) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf16 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf16, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf16 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf2
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf2)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf2, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf2)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf2) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf2 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf2, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf2 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf3
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf3)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf3, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf3)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf3) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf3 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf3, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf3 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf4
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf4)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf4, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf4)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf4) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf4 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf4, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf4 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf6
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf6)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf6, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf6)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf6) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf6 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf6, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf6 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf7
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf7)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf7, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf7)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf7) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf7 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf7, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf7 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf8
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf8)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf8, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf8)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf8) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf8 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf8, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf8 = nil
	}

	// try to unmarshal JSON data into V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9
	err = json.Unmarshal(data, &dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9)
	if err == nil {
		jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9, _ := json.Marshal(dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9)
		if string(jsonV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9) == "{}" { // empty struct
			dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9 = nil
		} else {
			return nil // data stored in dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9, return on the first match
		}
	} else {
		dst.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner) MarshalJSON() ([]byte, error) {
	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf1 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf1)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf10 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf10)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf11)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf12 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf12)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf13 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf13)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf14 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf14)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf15 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf15)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf16 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf16)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf2 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf2)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf3 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf3)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf4 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf4)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf5)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf6 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf6)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf7 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf7)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf8 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf8)
	}

	if src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9 != nil {
		return json.Marshal(&src.V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOf9)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner struct {
	value *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner
	isSet bool
}

func (v NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner) Get() *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner {
	return v.value
}

func (v *NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner) Set(val *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner(val *V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner) *NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner {
	return &NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner{value: val, isSet: true}
}

func (v NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
