/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf{}

// V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf struct for V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf
type V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf struct {
	// The point in time at which this value was made \"active\". `active_from` can be considered roughly analogous to `created_at`.
	ActiveFrom time.Time `json:"active_from"`
	// The point in time at which this value was deactivated. If `null`, the value is active.
	ActiveUntil    NullableTime                                                                           `json:"active_until"`
	CreatedByActor V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor `json:"created_by_actor"`
	// The type of the referenced actor. [Read more information on actor types here](/docs/actors).
	ReferencedActorType string `json:"referenced_actor_type"`
	// The ID of the referenced actor.
	ReferencedActorId NullableString `json:"referenced_actor_id"`
	// The attribute type of the value.
	AttributeType string `json:"attribute_type"`
}

type _V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf

// NewV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf instantiates a new V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf(activeFrom time.Time, activeUntil NullableTime, createdByActor V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor, referencedActorType string, referencedActorId NullableString, attributeType string) *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf {
	this := V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf{}
	this.ActiveFrom = activeFrom
	this.ActiveUntil = activeUntil
	this.CreatedByActor = createdByActor
	this.ReferencedActorType = referencedActorType
	this.ReferencedActorId = referencedActorId
	this.AttributeType = attributeType
	return &this
}

// NewV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOfWithDefaults instantiates a new V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOfWithDefaults() *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf {
	this := V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf{}
	return &this
}

// GetActiveFrom returns the ActiveFrom field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) GetActiveFrom() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ActiveFrom
}

// GetActiveFromOk returns a tuple with the ActiveFrom field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) GetActiveFromOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveFrom, true
}

// SetActiveFrom sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) SetActiveFrom(v time.Time) {
	o.ActiveFrom = v
}

// GetActiveUntil returns the ActiveUntil field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) GetActiveUntil() time.Time {
	if o == nil || o.ActiveUntil.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ActiveUntil.Get()
}

// GetActiveUntilOk returns a tuple with the ActiveUntil field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) GetActiveUntilOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActiveUntil.Get(), o.ActiveUntil.IsSet()
}

// SetActiveUntil sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) SetActiveUntil(v time.Time) {
	o.ActiveUntil.Set(&v)
}

// GetCreatedByActor returns the CreatedByActor field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) GetCreatedByActor() V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor {
	if o == nil {
		var ret V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor
		return ret
	}

	return o.CreatedByActor
}

// GetCreatedByActorOk returns a tuple with the CreatedByActor field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) GetCreatedByActorOk() (*V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedByActor, true
}

// SetCreatedByActor sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) SetCreatedByActor(v V2ObjectsObjectRecordsQueryPost200ResponseDataInnerValuesValueInnerAnyOfCreatedByActor) {
	o.CreatedByActor = v
}

// GetReferencedActorType returns the ReferencedActorType field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) GetReferencedActorType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferencedActorType
}

// GetReferencedActorTypeOk returns a tuple with the ReferencedActorType field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) GetReferencedActorTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferencedActorType, true
}

// SetReferencedActorType sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) SetReferencedActorType(v string) {
	o.ReferencedActorType = v
}

// GetReferencedActorId returns the ReferencedActorId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) GetReferencedActorId() string {
	if o == nil || o.ReferencedActorId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ReferencedActorId.Get()
}

// GetReferencedActorIdOk returns a tuple with the ReferencedActorId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) GetReferencedActorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferencedActorId.Get(), o.ReferencedActorId.IsSet()
}

// SetReferencedActorId sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) SetReferencedActorId(v string) {
	o.ReferencedActorId.Set(&v)
}

// GetAttributeType returns the AttributeType field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) GetAttributeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributeType
}

// GetAttributeTypeOk returns a tuple with the AttributeType field value
// and a boolean to check if the value has been set.
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) GetAttributeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributeType, true
}

// SetAttributeType sets field value
func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) SetAttributeType(v string) {
	o.AttributeType = v
}

func (o V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["active_from"] = o.ActiveFrom
	toSerialize["active_until"] = o.ActiveUntil.Get()
	toSerialize["created_by_actor"] = o.CreatedByActor
	toSerialize["referenced_actor_type"] = o.ReferencedActorType
	toSerialize["referenced_actor_id"] = o.ReferencedActorId.Get()
	toSerialize["attribute_type"] = o.AttributeType
	return toSerialize, nil
}

func (o *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"active_from",
		"active_until",
		"created_by_actor",
		"referenced_actor_type",
		"referenced_actor_id",
		"attribute_type",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf := _V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf)

	if err != nil {
		return err
	}

	*o = V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf(varV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf)

	return err
}

type NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf struct {
	value *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf
	isSet bool
}

func (v NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) Get() *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf {
	return v.value
}

func (v *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) Set(val *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf(val *V2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf {
	return &NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf{value: val, isSet: true}
}

func (v NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2ObjectsObjectRecordsPut200ResponseDataValuesValueInnerAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
