/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ScimV2UsersPost201ResponseRolesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimV2UsersPost201ResponseRolesInner{}

// ScimV2UsersPost201ResponseRolesInner struct for ScimV2UsersPost201ResponseRolesInner
type ScimV2UsersPost201ResponseRolesInner struct {
	Value   string `json:"value"`
	Primary bool   `json:"primary"`
}

type _ScimV2UsersPost201ResponseRolesInner ScimV2UsersPost201ResponseRolesInner

// NewScimV2UsersPost201ResponseRolesInner instantiates a new ScimV2UsersPost201ResponseRolesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimV2UsersPost201ResponseRolesInner(value string, primary bool) *ScimV2UsersPost201ResponseRolesInner {
	this := ScimV2UsersPost201ResponseRolesInner{}
	this.Value = value
	this.Primary = primary
	return &this
}

// NewScimV2UsersPost201ResponseRolesInnerWithDefaults instantiates a new ScimV2UsersPost201ResponseRolesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimV2UsersPost201ResponseRolesInnerWithDefaults() *ScimV2UsersPost201ResponseRolesInner {
	this := ScimV2UsersPost201ResponseRolesInner{}
	return &this
}

// GetValue returns the Value field value
func (o *ScimV2UsersPost201ResponseRolesInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201ResponseRolesInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ScimV2UsersPost201ResponseRolesInner) SetValue(v string) {
	o.Value = v
}

// GetPrimary returns the Primary field value
func (o *ScimV2UsersPost201ResponseRolesInner) GetPrimary() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Primary
}

// GetPrimaryOk returns a tuple with the Primary field value
// and a boolean to check if the value has been set.
func (o *ScimV2UsersPost201ResponseRolesInner) GetPrimaryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Primary, true
}

// SetPrimary sets field value
func (o *ScimV2UsersPost201ResponseRolesInner) SetPrimary(v bool) {
	o.Primary = v
}

func (o ScimV2UsersPost201ResponseRolesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimV2UsersPost201ResponseRolesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["primary"] = o.Primary
	return toSerialize, nil
}

func (o *ScimV2UsersPost201ResponseRolesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"primary",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varScimV2UsersPost201ResponseRolesInner := _ScimV2UsersPost201ResponseRolesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScimV2UsersPost201ResponseRolesInner)

	if err != nil {
		return err
	}

	*o = ScimV2UsersPost201ResponseRolesInner(varScimV2UsersPost201ResponseRolesInner)

	return err
}

type NullableScimV2UsersPost201ResponseRolesInner struct {
	value *ScimV2UsersPost201ResponseRolesInner
	isSet bool
}

func (v NullableScimV2UsersPost201ResponseRolesInner) Get() *ScimV2UsersPost201ResponseRolesInner {
	return v.value
}

func (v *NullableScimV2UsersPost201ResponseRolesInner) Set(val *ScimV2UsersPost201ResponseRolesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableScimV2UsersPost201ResponseRolesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableScimV2UsersPost201ResponseRolesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimV2UsersPost201ResponseRolesInner(val *ScimV2UsersPost201ResponseRolesInner) *NullableScimV2UsersPost201ResponseRolesInner {
	return &NullableScimV2UsersPost201ResponseRolesInner{value: val, isSet: true}
}

func (v NullableScimV2UsersPost201ResponseRolesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimV2UsersPost201ResponseRolesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
