/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"fmt"
)

// checks if the ConnectedFolder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectedFolder{}

// ConnectedFolder struct for ConnectedFolder
type ConnectedFolder struct {
	// The object slug or ID.
	Object string `json:"object"`
	// The ID of the record to create the file entry on.
	RecordId string `json:"record_id"`
	// The external storage provider.
	StorageProvider string `json:"storage_provider"`
	// The ID of the file or folder in the external storage provider.
	ExternalProviderFileId string `json:"external_provider_file_id"`
	// Microsoft drive ID. Only used when `storage_provider` is `microsoft-onedrive`.
	MicrosoftDriveId NullableString `json:"microsoft_drive_id,omitempty"`
	// Creates a connected folder entry.
	FileType             string `json:"file_type"`
	AdditionalProperties map[string]interface{}
}

type _ConnectedFolder ConnectedFolder

// NewConnectedFolder instantiates a new ConnectedFolder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectedFolder(object string, recordId string, storageProvider string, externalProviderFileId string, fileType string) *ConnectedFolder {
	this := ConnectedFolder{}
	this.Object = object
	this.RecordId = recordId
	this.StorageProvider = storageProvider
	this.ExternalProviderFileId = externalProviderFileId
	this.FileType = fileType
	return &this
}

// NewConnectedFolderWithDefaults instantiates a new ConnectedFolder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectedFolderWithDefaults() *ConnectedFolder {
	this := ConnectedFolder{}
	return &this
}

// GetObject returns the Object field value
func (o *ConnectedFolder) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *ConnectedFolder) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *ConnectedFolder) SetObject(v string) {
	o.Object = v
}

// GetRecordId returns the RecordId field value
func (o *ConnectedFolder) GetRecordId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecordId
}

// GetRecordIdOk returns a tuple with the RecordId field value
// and a boolean to check if the value has been set.
func (o *ConnectedFolder) GetRecordIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecordId, true
}

// SetRecordId sets field value
func (o *ConnectedFolder) SetRecordId(v string) {
	o.RecordId = v
}

// GetStorageProvider returns the StorageProvider field value
func (o *ConnectedFolder) GetStorageProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StorageProvider
}

// GetStorageProviderOk returns a tuple with the StorageProvider field value
// and a boolean to check if the value has been set.
func (o *ConnectedFolder) GetStorageProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageProvider, true
}

// SetStorageProvider sets field value
func (o *ConnectedFolder) SetStorageProvider(v string) {
	o.StorageProvider = v
}

// GetExternalProviderFileId returns the ExternalProviderFileId field value
func (o *ConnectedFolder) GetExternalProviderFileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExternalProviderFileId
}

// GetExternalProviderFileIdOk returns a tuple with the ExternalProviderFileId field value
// and a boolean to check if the value has been set.
func (o *ConnectedFolder) GetExternalProviderFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalProviderFileId, true
}

// SetExternalProviderFileId sets field value
func (o *ConnectedFolder) SetExternalProviderFileId(v string) {
	o.ExternalProviderFileId = v
}

// GetMicrosoftDriveId returns the MicrosoftDriveId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectedFolder) GetMicrosoftDriveId() string {
	if o == nil || IsNil(o.MicrosoftDriveId.Get()) {
		var ret string
		return ret
	}
	return *o.MicrosoftDriveId.Get()
}

// GetMicrosoftDriveIdOk returns a tuple with the MicrosoftDriveId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectedFolder) GetMicrosoftDriveIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MicrosoftDriveId.Get(), o.MicrosoftDriveId.IsSet()
}

// HasMicrosoftDriveId returns a boolean if a field has been set.
func (o *ConnectedFolder) HasMicrosoftDriveId() bool {
	if o != nil && o.MicrosoftDriveId.IsSet() {
		return true
	}

	return false
}

// SetMicrosoftDriveId gets a reference to the given NullableString and assigns it to the MicrosoftDriveId field.
func (o *ConnectedFolder) SetMicrosoftDriveId(v string) {
	o.MicrosoftDriveId.Set(&v)
}

// SetMicrosoftDriveIdNil sets the value for MicrosoftDriveId to be an explicit nil
func (o *ConnectedFolder) SetMicrosoftDriveIdNil() {
	o.MicrosoftDriveId.Set(nil)
}

// UnsetMicrosoftDriveId ensures that no value is present for MicrosoftDriveId, not even an explicit nil
func (o *ConnectedFolder) UnsetMicrosoftDriveId() {
	o.MicrosoftDriveId.Unset()
}

// GetFileType returns the FileType field value
func (o *ConnectedFolder) GetFileType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileType
}

// GetFileTypeOk returns a tuple with the FileType field value
// and a boolean to check if the value has been set.
func (o *ConnectedFolder) GetFileTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileType, true
}

// SetFileType sets field value
func (o *ConnectedFolder) SetFileType(v string) {
	o.FileType = v
}

func (o ConnectedFolder) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectedFolder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["record_id"] = o.RecordId
	toSerialize["storage_provider"] = o.StorageProvider
	toSerialize["external_provider_file_id"] = o.ExternalProviderFileId
	if o.MicrosoftDriveId.IsSet() {
		toSerialize["microsoft_drive_id"] = o.MicrosoftDriveId.Get()
	}
	toSerialize["file_type"] = o.FileType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectedFolder) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"record_id",
		"storage_provider",
		"external_provider_file_id",
		"file_type",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varConnectedFolder := _ConnectedFolder{}

	err = json.Unmarshal(data, &varConnectedFolder)

	if err != nil {
		return err
	}

	*o = ConnectedFolder(varConnectedFolder)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "object")
		delete(additionalProperties, "record_id")
		delete(additionalProperties, "storage_provider")
		delete(additionalProperties, "external_provider_file_id")
		delete(additionalProperties, "microsoft_drive_id")
		delete(additionalProperties, "file_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectedFolder struct {
	value *ConnectedFolder
	isSet bool
}

func (v NullableConnectedFolder) Get() *ConnectedFolder {
	return v.value
}

func (v *NullableConnectedFolder) Set(val *ConnectedFolder) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectedFolder) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectedFolder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectedFolder(val *ConnectedFolder) *NullableConnectedFolder {
	return &NullableConnectedFolder{value: val, isSet: true}
}

func (v NullableConnectedFolder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectedFolder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
