/*
Attio API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: support@attio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package libattio

import (
	"encoding/json"
	"fmt"
)

// NoteTagsInner struct for NoteTagsInner
type NoteTagsInner struct {
	NoteTagsInnerAnyOf                               *NoteTagsInnerAnyOf
	V2ObjectsRecordsSearchPostRequestRequestAsAnyOf1 *V2ObjectsRecordsSearchPostRequestRequestAsAnyOf1
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *NoteTagsInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into NoteTagsInnerAnyOf
	err = json.Unmarshal(data, &dst.NoteTagsInnerAnyOf)
	if err == nil {
		jsonNoteTagsInnerAnyOf, _ := json.Marshal(dst.NoteTagsInnerAnyOf)
		if string(jsonNoteTagsInnerAnyOf) == "{}" { // empty struct
			dst.NoteTagsInnerAnyOf = nil
		} else {
			return nil // data stored in dst.NoteTagsInnerAnyOf, return on the first match
		}
	} else {
		dst.NoteTagsInnerAnyOf = nil
	}

	// try to unmarshal JSON data into V2ObjectsRecordsSearchPostRequestRequestAsAnyOf1
	err = json.Unmarshal(data, &dst.V2ObjectsRecordsSearchPostRequestRequestAsAnyOf1)
	if err == nil {
		jsonV2ObjectsRecordsSearchPostRequestRequestAsAnyOf1, _ := json.Marshal(dst.V2ObjectsRecordsSearchPostRequestRequestAsAnyOf1)
		if string(jsonV2ObjectsRecordsSearchPostRequestRequestAsAnyOf1) == "{}" { // empty struct
			dst.V2ObjectsRecordsSearchPostRequestRequestAsAnyOf1 = nil
		} else {
			return nil // data stored in dst.V2ObjectsRecordsSearchPostRequestRequestAsAnyOf1, return on the first match
		}
	} else {
		dst.V2ObjectsRecordsSearchPostRequestRequestAsAnyOf1 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(NoteTagsInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src NoteTagsInner) MarshalJSON() ([]byte, error) {
	if src.NoteTagsInnerAnyOf != nil {
		return json.Marshal(&src.NoteTagsInnerAnyOf)
	}

	if src.V2ObjectsRecordsSearchPostRequestRequestAsAnyOf1 != nil {
		return json.Marshal(&src.V2ObjectsRecordsSearchPostRequestRequestAsAnyOf1)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableNoteTagsInner struct {
	value *NoteTagsInner
	isSet bool
}

func (v NullableNoteTagsInner) Get() *NoteTagsInner {
	return v.value
}

func (v *NullableNoteTagsInner) Set(val *NoteTagsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableNoteTagsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableNoteTagsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNoteTagsInner(val *NoteTagsInner) *NullableNoteTagsInner {
	return &NullableNoteTagsInner{value: val, isSet: true}
}

func (v NullableNoteTagsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNoteTagsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
